<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HobbySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('hobbies')->insert([
            ['name' => 'Watching Movies'],
            ['name' => 'Sports'],
            ['name' => 'Coding'],
            ['name' => 'Reading'],
            ['name' => 'Gardening'],
            ['name' => 'Hiking',],
            ['name' => 'Chess',],
            ['name' => 'Photography'],
            ['name' => 'Traveling'],
            ['name' => 'Cooking'],
            ['name' => 'Drawing'],
            ['name' => 'Painting'],
            ['name' => 'Writing'],
            ['name' => 'Dancing'],
            ['name' => 'Yoga'],
            ['name' => 'Meditation'],
            ['name' => 'Swimming'],
            ['name' => 'Fishing'],
            ['name' => 'Hiking'],
            ['name' => 'Camping'],
            ['name' => 'Gardening'],
            ['name' => 'Birdwatching'],
            ['name' => 'Cycling'],
            ['name' => 'Running'],
            ['name' => 'Knitting'],
            ['name' => 'Sewing'],
            ['name' => 'Woodworking'],
            ['name' => 'Pottery'],
            ['name' => 'Origami'],
            ['name' => 'Puzzles'],
            ['name' => 'Chess'],
            ['name' => 'Board Games'],
            ['name' => 'Card Games'],
            ['name' => 'Video Games'],
            ['name' => 'Baking'],
            ['name' => 'Cake Decorating'],
            ['name' => 'Learning Languages'],
            ['name' => 'Calligraphy'],
            ['name' => 'Scrapbooking'],
            ['name' => 'Journaling'],
            ['name' => 'Volunteering'],
            ['name' => 'Acting'],
            ['name' => 'Singing'],
            ['name' => 'Playing Instruments'],
            ['name' => 'Playing Guitar'],
            ['name' => 'Playing Piano'],
            ['name' => 'Playing Drums'],
            ['name' => 'Listening to Music'],
            ['name' => 'Watching TV Shows'],
            ['name' => 'Watching Documentaries'],
            ['name' => 'DIY Projects'],
            ['name' => 'Model Building'],
            ['name' => 'RC Cars'],
            ['name' => 'Astronomy'],
            ['name' => 'Star Gazing'],
            ['name' => 'Martial Arts'],
            ['name' => 'Pilates'],
            ['name' => 'Weightlifting'],
            ['name' => 'CrossFit'],
            ['name' => 'Skateboarding'],
            ['name' => 'Surfing'],
            ['name' => 'Skiing'],
            ['name' => 'Snowboarding'],
            ['name' => 'Rock Climbing'],
            ['name' => 'Scuba Diving'],
            ['name' => 'Snorkeling'],
            ['name' => 'Stand-up Paddleboarding'],
            ['name' => 'Kite Surfing'],
            ['name' => 'Paragliding'],
            ['name' => 'Bungee Jumping'],
            ['name' => 'Skydiving'],
            ['name' => 'Horseback Riding'],
            ['name' => 'Archery'],
            ['name' => 'Fencing'],
            ['name' => 'Boxing'],
            ['name' => 'Kickboxing'],
            ['name' => 'Tennis'],
            ['name' => 'Badminton'],
            ['name' => 'Table Tennis'],
            ['name' => 'Golf'],
            ['name' => 'Bowling'],
            ['name' => 'Ice Skating'],
            ['name' => 'Roller Skating'],
            ['name' => 'Salsa Dancing'],
            ['name' => 'Ballroom Dancing'],
            ['name' => 'Zumba'],
            ['name' => 'Tattoo Art'],
            ['name' => 'Fashion Design'],
            ['name' => 'Cosplay'],
            ['name' => 'Makeup Artistry'],
            ['name' => 'Jewelry Making'],
            ['name' => 'Leather Crafting'],
            ['name' => 'Soap Making'],
            ['name' => 'Candle Making'],
            ['name' => 'Perfume Making'],
            ['name' => 'Collecting Stamps'],
            ['name' => 'Collecting Coins'],
            ['name' => 'Collecting Action Figures'],
            ['name' => 'Collecting Vinyl Records'],
            ['name' => 'Collecting Antiques'],
            ['name' => 'Collecting Books'],
            ['name' => 'Collecting Postcards'],
            ['name' => 'Cosplaying'],
            ['name' => 'Role-Playing Games (RPG)'],
            ['name' => 'LARPing (Live Action Role-Playing)'],
            ['name' => 'Beekeeping'],
            ['name' => 'Dog Training'],
            ['name' => 'Aquascaping'],
            ['name' => 'Home Brewing'],
            ['name' => 'Winemaking'],
            ['name' => 'Car Restoration'],
            ['name' => 'Drone Flying'],
            ['name' => '3D Printing'],
            ['name' => 'Robotics'],
            ['name' => 'Coding'],
            ['name' => 'Building Computers'],
            ['name' => 'Cryptocurrency Trading'],
            ['name' => 'Investing'],
            ['name' => 'Podcasting'],
            ['name' => 'Vlogging'],
            ['name' => 'Blogging'],
            ['name' => 'Social Media Management'],
        ]);
    }
}
